version: '3.8'

services:
  reelgen:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./output:/app/output
      - ./processed_videos:/app/processed_videos
      - ./standardized_videos:/app/standardized_videos
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - PYTHONUNBUFFERED=1
    command: node dist/server.js
    restart: unless-stopped 